In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error, root_mean_squared_error, mean_absolute_error, accuracy_score, classification_report
from sklearn.preprocessing import PolynomialFeatures
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv('Lab_2/processed_titanic.csv')
df.head()

,PassengerId,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,num,HomePlanet_Europa,...,Destination_TRAPPIST-1e,VIP_True,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,deck_T,side_S
0,0013_01,0.341772,False,False,False,False,False,False,0.001587,False,...,True,False,False,False,False,False,False,True,False,True
1,0018_01,0.240506,False,False,False,False,False,False,0.002116,False,...,True,False,False,False,False,False,True,False,False,True
2,0019_01,0.392405,False,False,False,False,False,False,0.000000,True,...,False,False,False,True,False,False,False,False,False,True
3,0021_01,0.481013,False,False,False,False,False,False,0.000529,True,...,True,False,False,True,False,False,False,False,False,True
4,0023_01,0.253165,False,False,False,False,False,False,0.002646,False,...,True,False,False,False,False,False,True,False,False,True

In [3]:
# Regression

In [4]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(['num'], axis=1), df['num'], test_size=0.4, random_state=42)

x_train.head()

,PassengerId,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,HomePlanet_Europa,HomePlanet_Mars,...,Destination_TRAPPIST-1e,VIP_True,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,deck_T,side_S
3291,7211_01,0.392405,False,False,False,False,False,False,False,True,...,True,False,False,False,False,True,False,False,False,True
3945,8576_01,0.316456,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
801,1629_05,0.316456,False,False,False,False,False,False,True,False,...,True,False,True,False,False,False,False,False,False,True
2689,5911_06,0.126582,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
2131,4619_01,0.291139,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,True

In [5]:
linear_model = LinearRegression()

linear_model.fit(x_train, y_train)

y_pred = linear_model.predict(x_test)

rmse = root_mean_squared_error(y_test, y_pred)

print(rmse)
print(df['num'].describe())

0.11655815709393141
count    4277.000000
mean        0.320765
std         0.269601
min         0.000000
25%         0.094709
50%         0.233862
75%         0.535450
max         1.000000
Name: num, dtype: float64