In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error, root_mean_squared_error, mean_absolute_error, accuracy_score, classification_report
from sklearn.preprocessing import PolynomialFeatures
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv('processed_titanic.csv')
df.head()

,PassengerId,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,num,HomePlanet_Europa,...,Destination_TRAPPIST-1e,VIP_True,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,deck_T,side_S
0,0001_01,0.493671,False,False,False,False,False,False,0.000000,True,...,True,False,True,False,False,False,False,False,False,False
1,0002_01,0.303797,False,False,False,False,False,True,0.000000,False,...,True,False,False,False,False,False,True,False,False,True
2,0003_01,0.734177,True,True,True,True,True,False,0.000000,True,...,True,True,False,False,False,False,False,False,False,True
3,0003_02,0.417722,False,False,False,False,False,False,0.000000,True,...,True,False,False,False,False,False,False,False,False,True
4,0004_01,0.202532,False,False,False,False,False,True,0.000528,False,...,True,False,False,False,False,False,True,False,False,True

In [3]:
df_not_normalized = pd.read_csv('not normalized processed titanic.csv')
df_not_normalized.head()

,PassengerId,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,deck,num,side
0,0001_01,Europa,False,TRAPPIST-1e,39.0,False,False,False,False,False,False,False,B,0.0,P
1,0002_01,Earth,False,TRAPPIST-1e,24.0,False,False,False,False,False,False,True,F,0.0,S
2,0003_01,Europa,False,TRAPPIST-1e,58.0,True,True,True,True,True,True,False,A,0.0,S
3,0003_02,Europa,False,TRAPPIST-1e,33.0,False,False,False,False,False,False,False,A,0.0,S
4,0004_01,Earth,False,TRAPPIST-1e,16.0,False,False,False,False,False,False,True,F,1.0,S

In [4]:
# Regression

In [5]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(['num'], axis=1), df_not_normalized['num'], test_size=0.4, random_state=42)

x_train.head()

,PassengerId,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,HomePlanet_Europa,HomePlanet_Mars,...,Destination_TRAPPIST-1e,VIP_True,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,deck_T,side_S
4475,4757_01,0.303797,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,True
7118,7585_02,0.493671,False,False,False,False,False,False,True,False,...,True,False,False,True,False,False,False,False,False,True
7212,7705_01,0.582278,False,False,False,False,False,False,False,True,...,True,False,False,False,False,False,True,False,False,True
6982,7422_01,0.265823,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,True,False,True
8248,8813_01,0.518987,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True

In [6]:
linear_model = LinearRegression()

n = 2
poly_features = PolynomialFeatures(n)
x_train = poly_features.fit_transform(x_train)
poly_features = PolynomialFeatures(n)
x_test = poly_features.fit_transform(x_test)

linear_model.fit(x_train, y_train)

y_pred = linear_model.predict(x_test)

rmse = root_mean_squared_error(y_test, y_pred)

print(rmse)
print(df_not_normalized['num'].describe())

99.64779732050158
count    8693.000000
mean      596.398942
std       506.637799
min         0.000000
25%       173.000000
50%       427.000000
75%       983.000000
max      1894.000000
Name: num, dtype: float64

In [7]:
# Classification

In [8]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(['Transported'], axis=1), df['Transported'], test_size=0.4, random_state=42)

y_train.unique()

array([False,  True])

In [9]:
logreg_model = LogisticRegression()

logreg_model.fit(x_train, y_train)
y_pred = logreg_model.predict(x_test)

report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

       False       0.68      0.79      0.73      1714
        True       0.75      0.64      0.69      1764

    accuracy                           0.71      3478
   macro avg       0.72      0.71      0.71      3478
weighted avg       0.72      0.71      0.71      3478