In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error, root_mean_squared_error, mean_absolute_error, accuracy_score, classification_report
from sklearn.preprocessing import PolynomialFeatures
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [11]:
df = pd.read_csv('processed_titanic.csv')
df.head()

,PassengerId,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,num,HomePlanet_Europa,...,Destination_TRAPPIST-1e,VIP_True,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,deck_T,side_S
0,0013_01,0.341772,False,False,False,False,False,False,0.001587,False,...,True,False,False,False,False,False,False,True,False,True
1,0018_01,0.240506,False,False,False,False,False,False,0.002116,False,...,True,False,False,False,False,False,True,False,False,True
2,0019_01,0.392405,False,False,False,False,False,False,0.000000,True,...,False,False,False,True,False,False,False,False,False,True
3,0021_01,0.481013,False,False,False,False,False,False,0.000529,True,...,True,False,False,True,False,False,False,False,False,True
4,0023_01,0.253165,False,False,False,False,False,False,0.002646,False,...,True,False,False,False,False,False,True,False,False,True

In [3]:
df_not_normalized = pd.read_csv('not normalized processed titanic.csv')
df_not_normalized.head()

,PassengerId,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,deck,num,side
0,0013_01,Earth,True,TRAPPIST-1e,27.0,False,False,False,False,False,False,False,G,3.0,S
1,0018_01,Earth,False,TRAPPIST-1e,19.0,False,False,False,False,False,False,False,F,4.0,S
2,0019_01,Europa,True,55 Cancri e,31.0,False,False,False,False,False,False,False,C,0.0,S
3,0021_01,Europa,False,TRAPPIST-1e,38.0,False,False,False,False,False,False,False,C,1.0,S
4,0023_01,Earth,False,TRAPPIST-1e,20.0,False,False,False,False,False,False,False,F,5.0,S

In [4]:
# Regression

In [5]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(['num'], axis=1), df_not_normalized['num'], test_size=0.4, random_state=42)

x_train.head()

,PassengerId,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,HomePlanet_Europa,HomePlanet_Mars,...,Destination_TRAPPIST-1e,VIP_True,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,deck_T,side_S
3291,7211_01,0.392405,False,False,False,False,False,False,False,True,...,True,False,False,False,False,True,False,False,False,True
3945,8576_01,0.316456,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
801,1629_05,0.316456,False,False,False,False,False,False,True,False,...,True,False,True,False,False,False,False,False,False,True
2689,5911_06,0.126582,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
2131,4619_01,0.291139,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,True

In [6]:
linear_model = LinearRegression()

n = 2
poly_features = PolynomialFeatures(n)
x_train = poly_features.fit_transform(x_train)
poly_features = PolynomialFeatures(n)
x_test = poly_features.fit_transform(x_test)

linear_model.fit(x_train, y_train)

y_pred = linear_model.predict(x_test)

rmse = root_mean_squared_error(y_test, y_pred)

print(rmse)
print(df_not_normalized['num'].describe())

115.82137696186763
count    4277.000000
mean      606.246668
std       509.545187
min         0.000000
25%       179.000000
50%       442.000000
75%      1012.000000
max      1890.000000
Name: num, dtype: float64

In [7]:
# Classification

In [8]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(['Transported'], axis=1), df['Transported'], test_size=0.4, random_state=42)

y_train.unique()

array([False])

In [9]:
logreg_model = LogisticRegression()

logreg_model.fit(x_train, y_train)
y_pred = logreg_model.predict(x_test)

report = classification_report(y_test, y_pred)

ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: np.False_